### ISSUE TITLE
selectbox item을 동적으로 리로드하고 싶습니다.

### ISSUE THREAD

**Issue by kimhyosung** [nhn/toast-ui.select-box#5]
I'm not sure if I didn't look for an example or not.

I want to dynamically reload or modify an item (json string) in selectbox.

There is only a way to destroy and create a new one.

If there is a way to reload the entire item or change or set each item

Let me know-thank you

**Comment by dotaitch** [comment]
@kimhyosung 
Thank you for raising an issue.
First, I would like to ask for translating to English for other global users.

Currently, TOAST UI SelectBox does not provide the APIs to load items dynamically or change its value. However, I think it is a useful feature, so it will be taken into consideration. I will comment here if it is added.

**Comment by kimhyosung** [comment]
Thank. I solved it.
